### ISSUE TITLE
How do I load this system?

### ISSUE THREAD

**Issue by AndreasDavour** [isoraqathedh/cl-simple-fsm#1]
Hi, I quickloaded this system with quicklisp, and then tried to instantiate a finite-state-machine, but it failed. I guess I'm stupid, but what am I missing?

> (ql:quickload :finite-state-machine)
To load "finite-state-machine":
  Load 1 ASDF system:
    finite-state-machine
; Loading "finite-state-machine"

(:FINITE-STATE-MACHINE)
> (make-instance 'finite-state-machine 
			:states (list
				 :start
				 :sign
				 :decimal-point ...

There is no class named COMMON-LISP-USER::FINITE-STATE-MACHINE.
Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {10019830B3}>)

**Comment by isoraqathedh** [comment]
Ah, excuse me, you should name the package explicitly, like `info.isoraqathedh.finite-state-machine:finite-state-machine`, or import the symbol.

If you find the package name too long but you don't want to import the symbol or use the package, consider using `package-local-nicknames` for your implementation.

**Comment by AndreasDavour** [comment]
Oh, I missed that long package name! Too much information. Many thanks! Cheers.
